name: release_push

on:
  push:
    branches: [ "releases/**" ]
  workflow_dispatch:

jobs:
  post:
    if: github.event.created
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git_log
        run: |
          MESSAGE='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"<!here>\n<https://github.com/${{ github.repository }}|${{ github.repository }}>릴리즈 합니다.\n"}}]}'
          
          curl -X POST -H 'Content-type: application/json' --data "${MESSAGE}" "${{ secrets.SLACK_WEB_HOOK }}"
