name: release_push

on:
  push:
    branches: ["release/**"]
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
      # if: github.event.created
    steps:
      - uses: actions/checkout@v2
      - name: Debug Info
        run: |
          git remote update
          echo $(git branch)
          echo "Current Branch: $(git rev-parse --abbrev-ref HEAD)"
          FROM_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          TO_BRANCH="main"
          echo "From Branch: ${FROM_BRANCH}"
          echo "To Branch: ${TO_BRANCH}"
          COMMIT_MESSAGE=$(git log --format=%B origin/main..${FROM_BRANCH})
          echo "Commit Message: ${COMMIT_MESSAGE}"
      - name: post slack message
        run: |
          FROM_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          MESSAGE='{"blocks":[{"type":"header","text":{"type":"plain_text","text":":tada: 릴리즈 알림 :tada:","emoji":true}},{"type":"section","text":{"type":"mrkdwn","text":"*레포지토리:*\\n<https://github.com/${{ github.repository }}|${{ github.repository }}>\\n*브랜치:*\\n${FROM_BRANCH}"},"accessory":{"type":"image","image_url":"https://api.slack.com/img/blocks/bkb_template_images/approvalsNewDevice.png","alt_text":"computer thumbnail"}}]}'
          curl -X POST -H 'Content-type: application/json' --data '${MESSAGE}' "${{ secrets.SLACK_WEB_HOOK }}"
