name: release_push

on:
  push:
    branches: [ "releases/**" ]
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: git_log
        run: |
          git remote update
          echo "Current Branch: $(git rev-parse --abbrev-ref HEAD)"
          FROM_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          TO_BRANCH="main"
          echo "From Branch: ${FROM_BRANCH}"
          echo "To Branch: ${TO_BRANCH}"
          CM=$(git log --format=%B origin/main..${FROM_BRANCH})
          echo "${CM}"
          MESSAGE='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":"<!here>\n<https://github.com/${{ github.repository }}|${{ github.repository }}>릴리즈 합니다.\n${{CM}}}"}}]}'
          echo "${MESSAGE}"
          curl -X POST -H 'Content-type: application/json' --data "${MESSAGE}" "${{ secrets.SLACK_WEB_HOOK }}"
