name: release_push

on:
  push:
    branches: ["release/**"]
  workflow_dispatch:

jobs:
  post:
    runs-on:
      ubuntu-latest
      # if: github.event.created
    steps:
      - uses: actions/checkout@v2
      - name: post slack message
        run: |
          FROM_BRANCH=$(git rev-parse --abbrev-ref HEAD)
          MESSAGE='{"blocks":[{"type":"header","text":{"type":"plain_text","text":":tada: 릴리즈 알림 :tada:","emoji":true}},{"type":"section","text":{"type":"mrkdwn","text":"*레포지토리:*\n<https://github.com/${{ github.repository }}|${{ github.repository }}>\n*브랜치:*\n'"$FROM_BRANCH"'"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "${MESSAGE}" "${{ secrets.SLACK_WEB_HOOK }}"

